source 'https://github.com/cocoapods/Specs.git'

inhibit_all_warnings!
use_frameworks!

platform :ios, '9.0'

def appPods
    pod "ViperMcFlurryX", :path => "../ViperMcFlurryX.podspec"
    pod "Typhoon", '~> 4.0.0'
end

target 'ViperMcFlurry_Example' do
    appPods
end

target 'ViperMcFlurry_Tests' do
    appPods
end