source 'https://github.com/cocoapods/Specs.git'

inhibit_all_warnings!
use_frameworks!

platform :ios, '10.0'

def appPods
    pod "ViperMcFlurryX", :path => "../ViperMcFlurryX.podspec"
    pod "ViperMcFlurryX_Swift", :path => "../ViperMcFlurryX_Swift.podspec"
    pod "ViperMcFlurryX_Swift/EmbeddableModule", :path => "../ViperMcFlurryX_Swift.podspec"
    pod "OnDeallocateX"
    pod "Typhoon", '~> 4.0.0'
end

target 'ViperMcFlurry_Example' do
    appPods
end

target 'ViperMcFlurry_ExampleTests' do
    appPods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
